import { 
  AreaZone, 
  CommunityReport, 
  NotificationAlert, 
  Shelter, 
  UserProfile, 
  EncryptedStorageAudit,
  FamilySafetyStatus,
  GeotechSensorFeed,
  EvacuationRouteOption
} from '../types';

export const INITIAL_SHELTERS: Shelter[] = [
  {
    id: 'sh-01',
    name: 'Kalpetta District Emergency Relief Complex',
    address: 'NH 766 Bypass, Kalpetta Central',
    coordinates: [11.6085, 76.0825],
    capacity: 650,
    occupied: 280,
    status: 'open',
    amenities: ['24/7 Medical Clinic', 'Emergency Generator', 'Clean Drinking Water', 'Child Care', 'Food Distribution'],
    contactPhone: '+91 4936 202234',
    distanceKm: 4.2,
    foodStockDays: 14,
    medicalOfficerPresent: true,
  },
  {
    id: 'sh-02',
    name: 'Sultan Bathery Municipal Safe Zone',
    address: 'Govt Higher Secondary School Grounds, Bathery',
    coordinates: [11.6628, 76.2570],
    capacity: 900,
    occupied: 310,
    status: 'open',
    amenities: ['Large Dining Hall', 'Mobile Charging Stations', 'Ambulance Standby', 'Sanitation Blocks'],
    contactPhone: '+91 4936 220221',
    distanceKm: 12.8,
    foodStockDays: 20,
    medicalOfficerPresent: true,
  },
  {
    id: 'sh-03',
    name: 'Vythiri High-Plateau Community Center',
    address: 'Taluk Office Road, Old Vythiri',
    coordinates: [11.5512, 76.0410],
    capacity: 400,
    occupied: 365,
    status: 'near_capacity',
    amenities: ['Emergency First-Aid', 'Clean Water Purification', 'Satellite Phone Link'],
    contactPhone: '+91 4936 255300',
    distanceKm: 6.5,
    foodStockDays: 8,
    medicalOfficerPresent: true,
  },
  {
    id: 'sh-04',
    name: 'Meppadi Safe Evacuation Transit Camp',
    address: 'Govt Polytechnic Campus, Meppadi North',
    coordinates: [11.5540, 76.1280],
    capacity: 550,
    occupied: 540,
    status: 'full',
    amenities: ['Trauma Care', 'Helipad Access', 'Rescue Boat Station', 'Special Needs Care'],
    contactPhone: '+91 4936 282400',
    distanceKm: 2.1,
    foodStockDays: 5,
    medicalOfficerPresent: true,
  }
];

export const INITIAL_ZONES: AreaZone[] = [
  {
    id: 'zone-01',
    name: 'Chooralmala - Mundakkai Ridge',
    district: 'Wayanad Hill Sector',
    coordinates: [11.5385, 76.1680],
    rainfall24h: 196,
    rainfallRate1h: 28.4,
    soilMoisture: 95,
    slopeDegrees: 44,
    elevation: 1180,
    geologyType: 'Heavily Weathered Charnockite & Loose Colluvium Layer',
    vegetationCover: 32,
    population: 4350,
    criticalInfrastructure: ['Tea Factory Bridge (Choke Point)', 'Primary State Highway 54', 'Power Substation #4'],
    riskScore: 92,
    riskLevel: 'critical',
    xaiExplanation: 'CRITICAL RISK (92/100): Cumulative 24h rainfall (196mm) exceeded saturated pore-water trigger threshold by +68%. Slope gradient of 44° severely exceeds internal friction angle (31°). Soil pore water pressure reached 95% saturation with heavy debris flow probability on downstream residential cluster.',
    topContributingFactors: [
      { factor: 'Extreme 24h Rain Surge', impact: 94, description: '196mm recorded (180% of safety threshold)', status: 'danger' },
      { factor: 'Soil Pore Saturation', impact: 95, description: '95% capacity; liquefaction threshold reached', status: 'danger' },
      { factor: 'Steep Topography', impact: 88, description: '44° slope gradient with fractured regolith', status: 'danger' },
      { factor: 'Population Vulnerability', impact: 85, description: '4,350 residents in direct runout path', status: 'danger' },
    ],
    alertPriority: 'P1',
    evacuationStatus: 'mandatory',
    historicalLandslidesCount: 4,
    lastUpdated: 'Just now (Live Telemetry)',
    sheltersNearby: [INITIAL_SHELTERS[3], INITIAL_SHELTERS[0]],
    sensorHistory: [
      { time: '00:00', rainfall: 42, soilMoisture: 68, slopeTilt: 0.12 },
      { time: '04:00', rainfall: 78, soilMoisture: 75, slopeTilt: 0.18 },
      { time: '08:00', rainfall: 120, soilMoisture: 84, slopeTilt: 0.35 },
      { time: '12:00', rainfall: 165, soilMoisture: 91, slopeTilt: 0.62 },
      { time: '16:00', rainfall: 196, soilMoisture: 95, slopeTilt: 0.94 },
    ]
  },
  {
    id: 'zone-02',
    name: 'Puthumala Hill Scarp',
    district: 'Wayanad Hill Sector',
    coordinates: [11.5120, 76.1420],
    rainfall24h: 148,
    rainfallRate1h: 18.2,
    soilMoisture: 88,
    slopeDegrees: 39,
    elevation: 1320,
    geologyType: 'Fractured Granitic Gneiss over Clayey Subsoil',
    vegetationCover: 45,
    population: 2900,
    criticalInfrastructure: ['Tea Plantation Quarters', 'Ghat Access Link Road'],
    riskScore: 81,
    riskLevel: 'high',
    xaiExplanation: 'HIGH RISK (81/100): High antecedent moisture index (88%) paired with 148mm rainfall in 24 hours. Slope inclinometers report a 0.58° displacement on upper escarpment. Immediate evacuation recommended for lower terrace residents.',
    topContributingFactors: [
      { factor: 'Heavy Continuous Rain', impact: 82, description: '148mm over 24h period', status: 'danger' },
      { factor: 'Pore Water Pressure', impact: 88, description: '88% saturation in clayey interface', status: 'danger' },
      { factor: 'Inclinometer Shift', impact: 76, description: '0.58° surface creep observed', status: 'danger' },
      { factor: 'Slope Angle', impact: 78, description: '39° steep gradient', status: 'danger' },
    ],
    alertPriority: 'P1',
    evacuationStatus: 'advisory',
    historicalLandslidesCount: 3,
    lastUpdated: '3 mins ago',
    sheltersNearby: [INITIAL_SHELTERS[3], INITIAL_SHELTERS[2]],
    sensorHistory: [
      { time: '00:00', rainfall: 30, soilMoisture: 60, slopeTilt: 0.08 },
      { time: '04:00', rainfall: 62, soilMoisture: 70, slopeTilt: 0.14 },
      { time: '08:00', rainfall: 95, soilMoisture: 79, slopeTilt: 0.28 },
      { time: '12:00', rainfall: 128, soilMoisture: 84, slopeTilt: 0.44 },
      { time: '16:00', rainfall: 148, soilMoisture: 88, slopeTilt: 0.58 },
    ]
  },
  {
    id: 'zone-03',
    name: 'Vythiri Pass & Ghat Corridor',
    district: 'Thamarassery Churam Link',
    coordinates: [11.5580, 76.0350],
    rainfall24h: 86,
    rainfallRate1h: 9.5,
    soilMoisture: 69,
    slopeDegrees: 28,
    elevation: 910,
    geologyType: 'Laterite Crust over Metasedimentary Bedrock',
    vegetationCover: 68,
    population: 6800,
    criticalInfrastructure: ['National Highway 766 (Hairpin Bends 5-9)', 'Emergency Fuel Depot'],
    riskScore: 54,
    riskLevel: 'medium',
    xaiExplanation: 'MEDIUM RISK (54/100): Moderate rainfall of 86mm. Slope stability is partially buffered by 68% tree canopy, but roadside cuttings and hairpin road culverts are experiencing high runoff velocity. Heavy vehicular traffic restricted.',
    topContributingFactors: [
      { factor: 'Roadside Embankment Stress', impact: 65, description: 'High runoff velocity along NH-766 cuts', status: 'caution' },
      { factor: 'Soil Saturation', impact: 69, description: '69% moisture; watch for rock slips', status: 'caution' },
      { factor: 'Moderate Rainfall', impact: 52, description: '86mm 24h total', status: 'caution' },
      { factor: 'Vegetation Shield', impact: 32, description: 'High canopy helps retain root shear strength', status: 'safe' },
    ],
    alertPriority: 'P2',
    evacuationStatus: 'none',
    historicalLandslidesCount: 2,
    lastUpdated: '12 mins ago',
    sheltersNearby: [INITIAL_SHELTERS[2], INITIAL_SHELTERS[0]],
    sensorHistory: [
      { time: '00:00', rainfall: 18, soilMoisture: 48, slopeTilt: 0.02 },
      { time: '04:00', rainfall: 35, soilMoisture: 54, slopeTilt: 0.04 },
      { time: '08:00', rainfall: 52, soilMoisture: 61, slopeTilt: 0.07 },
      { time: '12:00', rainfall: 71, soilMoisture: 65, slopeTilt: 0.10 },
      { time: '16:00', rainfall: 86, soilMoisture: 69, slopeTilt: 0.12 },
    ]
  },
  {
    id: 'zone-04',
    name: 'Mananthavady River Slope',
    district: 'North Wayanad Sector',
    coordinates: [11.8020, 76.0040],
    rainfall24h: 58,
    rainfallRate1h: 6.2,
    soilMoisture: 55,
    slopeDegrees: 21,
    elevation: 760,
    geologyType: 'Riverine Alluvium with Cohesive Silt',
    vegetationCover: 72,
    population: 5200,
    criticalInfrastructure: ['Kabini River Bridge', 'Community Hospital'],
    riskScore: 38,
    riskLevel: 'medium',
    xaiExplanation: 'MEDIUM RISK (38/100): River bank erosion observed along lower contours. Soil moisture at 55%. No imminent slope failure, but continuous monitoring of river surge is active.',
    topContributingFactors: [
      { factor: 'Bank Under-cutting', impact: 48, description: 'River current eroding toe of slope', status: 'caution' },
      { factor: 'Soil Moisture', impact: 55, description: 'Moderate saturation', status: 'caution' },
      { factor: 'Gentle Incline', impact: 28, description: '21° slope is generally stable', status: 'safe' },
      { factor: 'High Canopy', impact: 22, description: 'Good root network', status: 'safe' },
    ],
    alertPriority: 'P3',
    evacuationStatus: 'none',
    historicalLandslidesCount: 1,
    lastUpdated: '18 mins ago',
    sheltersNearby: [INITIAL_SHELTERS[0], INITIAL_SHELTERS[1]],
    sensorHistory: [
      { time: '00:00', rainfall: 10, soilMoisture: 42, slopeTilt: 0.01 },
      { time: '04:00', rainfall: 22, soilMoisture: 46, slopeTilt: 0.02 },
      { time: '08:00', rainfall: 36, soilMoisture: 50, slopeTilt: 0.03 },
      { time: '12:00', rainfall: 48, soilMoisture: 53, slopeTilt: 0.04 },
      { time: '16:00', rainfall: 58, soilMoisture: 55, slopeTilt: 0.05 },
    ]
  },
  {
    id: 'zone-05',
    name: 'Sultan Bathery High Plateau',
    district: 'East Plateau Zone',
    coordinates: [11.6620, 76.2620],
    rainfall24h: 24,
    rainfallRate1h: 2.1,
    soilMoisture: 36,
    slopeDegrees: 9,
    elevation: 935,
    geologyType: 'Flat Basalt & Compacted Quartzite Plateau',
    vegetationCover: 80,
    population: 19500,
    criticalInfrastructure: ['Municipal Civil Station', 'Designated Central Relief Staging Ground'],
    riskScore: 14,
    riskLevel: 'low',
    xaiExplanation: 'LOW RISK (14/100): Minimal precipitation (24mm), gentle 9° slope, well-drained tableland. Designated as Primary Safe Haven & Logistics Hub for evacuees.',
    topContributingFactors: [
      { factor: 'Plateau Topography', impact: 10, description: 'Very low 9° gradient', status: 'safe' },
      { factor: 'Low Rainfall', impact: 15, description: '24mm over 24h', status: 'safe' },
      { factor: 'Pore Pressure', impact: 36, description: 'Dry to well-drained soil structure', status: 'safe' },
      { factor: 'Structural Stability', impact: 8, description: 'Solid crystalline basement bedrock', status: 'safe' },
    ],
    alertPriority: 'P3',
    evacuationStatus: 'none',
    historicalLandslidesCount: 0,
    lastUpdated: '5 mins ago',
    sheltersNearby: [INITIAL_SHELTERS[1]],
    sensorHistory: [
      { time: '00:00', rainfall: 4, soilMoisture: 32, slopeTilt: 0.00 },
      { time: '04:00', rainfall: 8, soilMoisture: 33, slopeTilt: 0.00 },
      { time: '08:00', rainfall: 14, soilMoisture: 34, slopeTilt: 0.00 },
      { time: '12:00', rainfall: 19, soilMoisture: 35, slopeTilt: 0.01 },
      { time: '16:00', rainfall: 24, soilMoisture: 36, slopeTilt: 0.01 },
    ]
  },
  {
    id: 'zone-06',
    name: 'Kalpetta Valley Basin',
    district: 'Central Administrative Valley',
    coordinates: [11.6110, 76.0840],
    rainfall24h: 34,
    rainfallRate1h: 3.4,
    soilMoisture: 42,
    slopeDegrees: 12,
    elevation: 780,
    geologyType: 'Granulite Basement with Deep Red Loam',
    vegetationCover: 75,
    population: 26000,
    criticalInfrastructure: ['District Emergency Operation Center (DEOC)', 'Main General Hospital', 'Helipad'],
    riskScore: 19,
    riskLevel: 'low',
    xaiExplanation: 'LOW RISK (19/100): Stable valley floor conditions. Soil saturation at safe 42%. Base station operational for emergency command.',
    topContributingFactors: [
      { factor: 'Valley Elevation', impact: 14, description: 'Stable 12° slope', status: 'safe' },
      { factor: 'Low Rainfall', impact: 20, description: '34mm recorded', status: 'safe' },
      { factor: 'Infrastructure Preparedness', impact: 12, description: 'Emergency DEOC active', status: 'safe' },
      { factor: 'Moisture Capacity', impact: 42, description: 'Ample absorption capacity remaining', status: 'safe' },
    ],
    alertPriority: 'P3',
    evacuationStatus: 'none',
    historicalLandslidesCount: 0,
    lastUpdated: '10 mins ago',
    sheltersNearby: [INITIAL_SHELTERS[0]],
    sensorHistory: [
      { time: '00:00', rainfall: 6, soilMoisture: 38, slopeTilt: 0.00 },
      { time: '04:00', rainfall: 12, soilMoisture: 39, slopeTilt: 0.00 },
      { time: '08:00', rainfall: 20, soilMoisture: 40, slopeTilt: 0.01 },
      { time: '12:00', rainfall: 28, soilMoisture: 41, slopeTilt: 0.01 },
      { time: '16:00', rainfall: 34, soilMoisture: 42, slopeTilt: 0.01 },
    ]
  }
];

export const INITIAL_REPORTS: CommunityReport[] = [
  {
    id: 'rep-001',
    reporterId: 'usr-cit-101',
    reporterName: 'Anand Nair',
    reporterRole: 'citizen',
    isVerifiedCitizen: true,
    type: 'ground_crack',
    severity: 'critical',
    description: 'Noticed a 15-meter long longitudinal ground tension crack (width ~8cm) developing across the plantation terrace just above the upper residential lane. Water bubbling out from the lower fissure.',
    locationName: 'Chooralmala Upper Tea Estate Sector 4',
    coordinates: [11.5420, 76.1620],
    timestamp: '18 mins ago',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18015f6?auto=format&fit=crop&w=600&q=80',
    status: 'verified',
    assignedTeam: 'Rapid Geotechnical Unit Alpha',
    encryptedHash: 'ENC_GCM_N2Q3NGYwMjk4ZmMxYzE0OWFmYmY0Yzg5OTZmYjkyNDI3YWU0MWU0NjQ5YjkzNGNhNDk1OTkxYjc4NTJiODU1',
    sha256Checksum: 'e28f14c2b9a7c36a8d0551ef9518d6e9bc630138977114620ca63116812be2b1',
    isEncrypted: true,
    upvotes: 24,
    authorityNotes: 'Verified by Field Geologist. Evacuation protocol initiated for lower 40 households.'
  },
  {
    id: 'rep-002',
    reporterId: 'usr-cit-102',
    reporterName: 'Priya Varghese',
    reporterRole: 'citizen',
    isVerifiedCitizen: true,
    type: 'falling_rocks',
    severity: 'high',
    description: 'Small boulder dislodgement and continuous shale rockfalls occurring near Hairpin Curve #7. One lane is blocked and mud slush is covering the road surface.',
    locationName: 'NH-766 Ghat Hairpin Curve 7',
    coordinates: [11.5590, 76.0390],
    timestamp: '42 mins ago',
    imageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=600&q=80',
    status: 'dispatched',
    assignedTeam: 'Highways Emergency Clearance Crew 2',
    encryptedHash: 'ENC_GCM_ZjEwOWMyOGU3NDQyYTExYzg0ODkyMTkyOGU3MmI5MWNmYTg5M2Q4ZjA3NzI3ODU2',
    sha256Checksum: 'a8b1c4e7f9102456b3e945c71184a2f8b502938475a1b2c3d4e5f60718293a4b',
    isEncrypted: true,
    upvotes: 18,
    authorityNotes: 'Excavator and earthmover en route. Traffic police diverting heavy vehicles via Mananthavady.'
  },
  {
    id: 'rep-003',
    reporterId: 'usr-cit-103',
    reporterName: 'Mohammed Rasheed',
    reporterRole: 'citizen',
    isVerifiedCitizen: false,
    type: 'water_leakage',
    severity: 'medium',
    description: 'Sudden brown turbid muddy water springing out from the retaining wall weep holes behind the panchayat community hall.',
    locationName: 'Meppadi North Panchayat Road',
    coordinates: [11.5510, 76.1310],
    timestamp: '1 hour ago',
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80',
    status: 'pending',
    encryptedHash: 'ENC_GCM_YTI4ZmM5OTBhOGY1ZTE2N2Y0NGY0OTY0ZTY',
    sha256Checksum: '9f8e7d6c5b4a3210fedcba9876543210123456789abcdef0123456789abcdef0',
    isEncrypted: true,
    upvotes: 7,
    authorityNotes: 'Pending field inspector triage.'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationAlert[] = [
  {
    id: 'notif-01',
    title: 'RED ALERT: Evacuation Order for Chooralmala',
    message: 'State Disaster Management Authority has issued an immediate mandatory evacuation order for Chooralmala - Mundakkai Ridge due to critical soil pore saturation (95%) and active tension cracks. Proceed immediately to Shelter #4 or Kalpetta Relief Camp.',
    severity: 'critical',
    priority: 'P1',
    timestamp: '10 mins ago',
    areaId: 'zone-01',
    areaName: 'Chooralmala - Mundakkai Ridge',
    targetAudience: 'all',
    isRead: false,
    broadcastedBy: 'District Emergency Operations Center (DEOC)',
    soundAlarm: true
  },
  {
    id: 'notif-02',
    title: 'Traffic Advisory: Ghat Road Rockfall Warning',
    message: 'Rockfall and debris movement reported near NH-766 Hairpin Bend 7. Heavy commercial transit is suspended. Light vehicles exercise extreme caution.',
    severity: 'warning',
    priority: 'P2',
    timestamp: '35 mins ago',
    areaId: 'zone-03',
    areaName: 'Vythiri Pass & Ghat Corridor',
    targetAudience: 'all',
    isRead: false,
    broadcastedBy: 'Traffic Command & Highway Safety'
  },
  {
    id: 'notif-03',
    title: 'Weather Radar: 24h Heavy Rain Inflow Forecast',
    message: 'IMD Doppler Radar indicates deep convective clouds over high-altitude Western Ghats. Rainfall intensity expected to exceed 30mm/hr through midnight.',
    severity: 'info',
    priority: 'P3',
    timestamp: '1 hour ago',
    targetAudience: 'all',
    isRead: true,
    broadcastedBy: 'Meteorological Risk Bureau'
  }
];

export const INITIAL_AUDIT_LOGS: EncryptedStorageAudit[] = [
  {
    id: 'aud-001',
    recordId: 'rep-001',
    recordType: 'community_report',
    encryptionAlgorithm: 'AES-256-GCM (Zero-Knowledge Envelope)',
    ivHex: '3a8f9c1b7e2d5a4c9b0e1f3a',
    cipherSnippet: 'g5k9P...xQ8z==',
    sha256Checksum: 'e28f14c2b9a7c36a8d0551ef9518d6e9bc630138977114620ca63116812be2b1',
    lastModified: '2026-08-31T09:12:00Z',
    encryptedBy: 'Client WebCrypto Engine v2.4'
  },
  {
    id: 'aud-002',
    recordId: 'usr-cit-101',
    recordType: 'citizen_identity',
    encryptionAlgorithm: 'AES-256-GCM + PBKDF2 (100k iters)',
    ivHex: '8c4b2a1e9f0d7c3b5a2e6f1a',
    cipherSnippet: 'm9V1x...wL3k==',
    sha256Checksum: 'b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9',
    lastModified: '2026-08-31T08:45:00Z',
    encryptedBy: 'Citizen Identity Shield'
  },
  {
    id: 'aud-003',
    recordId: 'zone-01-telemetry',
    recordType: 'telemetry_stream',
    encryptionAlgorithm: 'AES-256-GCM Sensor Tunnel',
    ivHex: '1e3d5c7b9a2f4e6d8c0b2a4e',
    cipherSnippet: 'rT4yU...pM2q==',
    sha256Checksum: 'd4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35',
    lastModified: '2026-08-31T09:15:30Z',
    encryptedBy: 'IoT Edge Gateway Gateway-9'
  }
];

export const DEMO_CITIZEN_USER: UserProfile = {
  id: 'usr-cit-01',
  name: 'Lakshmi Menon',
  email: 'lakshmi.menon@kerala.res.in',
  phone: '+91 98471 23456',
  role: 'citizen',
  isVerified: true,
  verificationBadgeNumber: 'IN-KL-WY-2026-V8824',
  trustedReporterScore: 96,
  currentLocationName: 'Chooralmala Sector, Wayanad',
  currentCoordinates: [11.5390, 76.1650],
  emergencyContacts: [
    { name: 'Dr. Suresh Menon (Brother)', relation: 'Immediate Family', phone: '+91 94470 11223' },
    { name: 'Meppadi Ward Member Office', relation: 'Local Authority', phone: '+91 4936 282210' },
    { name: 'District Disaster Helpline', relation: 'Emergency Desk', phone: '1077' }
  ]
};

export const DEMO_AUTHORITY_USER: UserProfile = {
  id: 'usr-auth-01',
  name: 'Cmdr. Rajesh K. Varma',
  email: 'rajesh.varma@sdma.gov.in',
  phone: '+91 94479 99001',
  role: 'incident_commander',
  isVerified: true,
  badgeId: 'SDMA-IC-9021',
  department: 'State Disaster Management Authority (SDMA) & NDRF Joint Taskforce',
  assignedSector: 'Wayanad High Hazard Zone (Sector-A)',
  verificationBadgeNumber: 'GOV-AUTH-COMMAND-9021',
};

export const INITIAL_FAMILY_CHECKINS: FamilySafetyStatus[] = [
  {
    id: 'fcheck-1',
    userName: 'Lakshmi Menon & Family (3)',
    userPhone: '+91 94470 11223',
    status: 'at_shelter',
    locationName: 'Meppadi Safe Transit Camp #4',
    coordinates: [11.5540, 76.1280],
    timestamp: '12 mins ago',
    notes: 'Safe at Hall B, battery 68%, all family members accounted for.',
    batteryLevel: 68,
    relayMethod: 'cloud',
    verifiedIdentity: true,
  },
  {
    id: 'fcheck-2',
    userName: 'Rahul Nair',
    userPhone: '+91 98461 44556',
    status: 'evacuating',
    locationName: 'En route via NH 766 Bypass',
    coordinates: [11.5800, 76.1100],
    timestamp: '28 mins ago',
    notes: 'Moving towards Kalpetta Complex on foot with neighbors.',
    batteryLevel: 42,
    relayMethod: 'mesh_bluetooth',
    verifiedIdentity: true,
  },
  {
    id: 'fcheck-3',
    userName: 'Anand & Divya George',
    userPhone: '+91 94950 88990',
    status: 'safe',
    locationName: 'Vythiri High-Plateau Resident Area',
    coordinates: [11.5512, 76.0410],
    timestamp: '45 mins ago',
    notes: 'Staying on 2nd floor, slope stable behind property.',
    batteryLevel: 85,
    relayMethod: 'cloud',
    verifiedIdentity: true,
  },
  {
    id: 'fcheck-4',
    userName: 'Eldo K. Varghese',
    userPhone: '+91 97441 33221',
    status: 'need_help',
    locationName: 'Upper Tea Quarters, Sector 2',
    coordinates: [11.5360, 76.1620],
    timestamp: '1 hr ago',
    notes: 'Elderly person with mobility assistance needed. Bridge flooded.',
    batteryLevel: 19,
    relayMethod: 'emergency_sms',
    verifiedIdentity: false,
  },
];

export const INITIAL_IOT_SENSORS: GeotechSensorFeed[] = [
  {
    sensorId: 'SEN-PZ-901',
    zoneId: 'zone-01',
    sensorType: 'pore_piezometer',
    label: 'Vibrating Wire Piezometer #01',
    currentVal: 142.8,
    unit: 'kPa',
    thresholdWarning: 100.0,
    thresholdCritical: 130.0,
    status: 'critical',
    waveform: [65, 72, 85, 98, 112, 128, 139, 142.8],
    batteryPercent: 88,
    lastPacketTime: 'Just now (Radio LoRa)',
  },
  {
    sensorId: 'SEN-INC-402',
    zoneId: 'zone-01',
    sensorType: 'tilt_inclinometer',
    label: 'Borehole Inclinometer Probe Alpha',
    currentVal: 4.85,
    unit: 'mm/hr',
    thresholdWarning: 2.0,
    thresholdCritical: 4.0,
    status: 'critical',
    waveform: [0.2, 0.4, 0.9, 1.8, 2.7, 3.8, 4.4, 4.85],
    batteryPercent: 92,
    lastPacketTime: 'Just now (Radio LoRa)',
  },
  {
    sensorId: 'SEN-AE-108',
    zoneId: 'zone-01',
    sensorType: 'acoustic_emission',
    label: 'Micro-Seismic Acoustic Wave Receiver',
    currentVal: 184,
    unit: 'Hits/min',
    thresholdWarning: 60,
    thresholdCritical: 120,
    status: 'critical',
    waveform: [12, 18, 24, 55, 95, 130, 160, 184],
    batteryPercent: 79,
    lastPacketTime: 'Just now (LoRa Mesh)',
  },
  {
    sensorId: 'SEN-VWC-204',
    zoneId: 'zone-02',
    sensorType: 'soil_moisture_probe',
    label: 'FDR Soil Dielectric Moisture Sensor',
    currentVal: 88.4,
    unit: '%',
    thresholdWarning: 75.0,
    thresholdCritical: 90.0,
    status: 'warning',
    waveform: [45, 52, 60, 71, 78, 82, 86, 88.4],
    batteryPercent: 95,
    lastPacketTime: '1 min ago (Telemetry Gateway)',
  },
  {
    sensorId: 'SEN-INC-501',
    zoneId: 'zone-03',
    sensorType: 'tilt_inclinometer',
    label: 'NH-766 Road Embankment Tilt Sensor',
    currentVal: 0.82,
    unit: 'mm/hr',
    thresholdWarning: 2.0,
    thresholdCritical: 4.0,
    status: 'normal',
    waveform: [0.3, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.82],
    batteryPercent: 98,
    lastPacketTime: '4 mins ago (Cellular NB-IoT)',
  }
];

export const INITIAL_EVACUATION_ROUTES: EvacuationRouteOption[] = [
  {
    id: 'route-opt-1',
    title: 'Primary Safe Highland Ridge Path',
    destinationShelterId: 'sh-04',
    shelterName: 'Meppadi Safe Evacuation Transit Camp',
    distanceKm: 2.4,
    estWalkTimeMin: 28,
    safetyScore: 94,
    hazardAvoidanceNotes: [
      'Avoids flooded river basin and washed-out tea factory bridge',
      'Follows stable basalt ridge bedrock with steady drainage',
      'Solar-powered emergency trail markers illuminated'
    ],
    elevationGain: 45,
    pathCoordinates: [
      [11.5385, 76.1680],
      [11.5420, 76.1590],
      [11.5480, 76.1450],
      [11.5540, 76.1280],
    ],
    isRecommended: true,
  },
  {
    id: 'route-opt-2',
    title: 'North Plateau Bypass via Kalpetta Link',
    destinationShelterId: 'sh-01',
    shelterName: 'Kalpetta District Emergency Relief Complex',
    distanceKm: 4.8,
    estWalkTimeMin: 55,
    safetyScore: 82,
    hazardAvoidanceNotes: [
      'Longer route suitable for light 4WD vehicles and escorted groups',
      'Passes through stable rubber plantation plateau',
      'NDRF escort checkpoint active at Kilometer 2.1'
    ],
    elevationGain: 80,
    pathCoordinates: [
      [11.5385, 76.1680],
      [11.5600, 76.1400],
      [11.5850, 76.1100],
      [11.6085, 76.0825],
    ],
    isRecommended: false,
  }
];
